assets:
    disableHLJS: false
title: notes by sourcevault
description: "ExampleSite description"
keywords: [Blog, Portfolio, PaperMod]
author: sourcevault
# author: ["Me", "You"] # multiple authors
DateFormat: "January 2, 2006"
defaultTheme: dark # dark, light
disableThemeToggle: false
ShowReadingTime: true
ShowBreadCrumbs: true
ShowCodeCopyButtons: true
disableSpecial1stPost: false
disableScrollToTop: false
comments: false
hidemeta: false
hideSummary: false
showtoc: true
tocopen: false
# https://fusejs.io/api/options.html
fuseOpts:
  isCaseSensitive: false
  shouldSort: true
  location: 0
  distance: 1000
  threshold: 0.4
  minMatchCharLength: 0
  keys: ["title", "permalink", "summary", "content"]
comments: true